rosdistro: 'melodic

  '
roslaunch:
  uris: {host_hp__42427: 'http://HP:42427/'}
rosversion: '1.14.9

  '
run_id: ca6e7d62-09d7-11eb-8f1a-c8215820abb6
turtlesim: {background_b: 255, background_g: 86, background_r: 69}
