# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: white_arm
  joint_model_group_pose: home_pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - waist1_joint
    - waist2_joint
    - waist3_joint
    - black1_joint
    - black2_joint
    - black3_joint
    - black4_joint
    - black5_joint
    - black6_joint
    - black7_joint
    - neck1_joint
    - neck2_joint
    - white1_joint
    - white2_joint
    - white3_joint
    - white4_joint
    - white5_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
torso_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - waist1_joint
    - waist2_joint
    - waist3_joint
    - neck1_joint
    - neck2_joint
  gains:
    waist1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    waist2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    waist3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    neck1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    neck2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
black_arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - black1_joint
    - black2_joint
    - black3_joint
    - black4_joint
    - black5_joint
    - black6_joint
    - black7_joint
  gains:
    black1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    black2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    black3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    black4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    black5_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    black6_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    black7_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
white_arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - white1_joint
    - white2_joint
    - white3_joint
    - white4_joint
    - white5_joint
  gains:
    white1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    white2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    white3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    white4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    white5_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1